package ShellNightmare.Terminal.FileSystem;


/**
 * enumeration indiquant les erreurs qui peuvent intervenir lors de la manipulation de commandes
 * @author Gaëtan Lounes
 */
public enum E_IOStatus {
    OK, PERMISSION, ALREADY_EXIST, NOT_EXIST, TRY_REMOVING_FOLDER,NOT_A_FOLDER, FOLDER_IS_NOT_EMPTY,TRY_REMOVING_ROOT, EMPTY, MISSING_NEEDED_PARAMETERS, INVALID_OPTION, CRITICAL_BUG,
    INVALID_USER,ALREADY_EXIST_USER, ALREADY_EXIST_GROUP, INVALID_PASSWORD, INVALID_GROUP, USER_NOT_IN_GROUP, INVALID_COMMAND, INVALID_VAR, INVALID_NUMBER,IS_NOT_DATA, INVALID_NAME
}
